### ISSUE TITLE
It`s possible to modify the ip/port scanner inside sshscanner ?

### ISSUE THREAD

**Issue by Prostu2** [maesoser/sshscan#2]
It takes ages to scan a B class, A class will finish in 2040.
U could add something like synscan within or i could try, but it will take me longer that you .. 
Sorry if i `m un polite :dancer:

**Comment by maesoser** [comment]
Hi Prostu2!

I designed this scanner to work on home sized networks. But, anyway, what you're saying is interesting. If I'm getting it well, you propose to make a quick and asynchronous syn scan _before_ doing the ssh handshakes in order to reduce the number of host in which such handshake is performed, right? This is interesting and I'll think about it, but I can't promise a quick pull with this improvement.

Meanwhile, you can increase the number of threads the scanner uses or you can use another profesional tool like the ones I talk about on the README.

BR

Sergio.

**Comment by Prostu2** [comment]
I like yours better
If you can modify it to work on a list of allready scanned server .. :D

**Comment by maesoser** [comment]
I'm pretty sure you'll be able to! I'm currently quite busy so It could take some time for me to release such feature...
